products_screen As screen:
    Fill: =RGBA(232, 232, 232, 1)
    OnVisible: =Set(showNav,false)

    screen_title_2 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 89, 178, 1)
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Fill: =RGBA(0, 36, 71, 1)
        Size: =13
        Text: =""
        Width: =Parent.Width
        ZIndex: =1

    nav_icon_2 As icon.Waffle:
        BorderColor: =RGBA(0, 0, 0, 0)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(244, 244, 244, 1)
        FocusedBorderThickness: =0
        Height: =38
        Icon: =Icon.Waffle
        OnSelect: =If(showNav,Set(showNav,false),Set(showNav,true))
        Width: |
            =38
        X: =1
        Y: =1
        ZIndex: =2

    screen_logo_2 As image:
        BorderColor: =RGBA(0, 89, 178, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Fill: =RGBA(250, 250, 250, 1)
        Height: =screen_title_2.Height*2
        Image: |-
            =Xinet.GetImageByPath("getimage","/vol03/Walmart Assets/Common_Elements/WM_LockUps_Icons_etc/Walmart_SMLB_2020_logo_Revised_TM_MC/Walmart_SMLB_2020_RGB_EN.ai",{filetype:"large"})
        ImagePosition: =ImagePosition.Fill
        Width: =220
        X: =Parent.Width-Self.Width-Self.BorderThickness
        ZIndex: =3

